### PR TITLE
Update to allow ruby 2 and 3

### PR DESCRIPTION
**Pull request by malikarun**

### CODE REVIEW

**Review by nathanaelkane — APPROVED** [review]
Haven't manually tested, but code looks fine.

**Comment by jasoncodes** [comment]
I suggested the range of 2.7 to 3.0 but am now thinking we should try for 3.2 support as that comes out this month. Going to do a little bit of isolated testing. We should probably also bump `.ruby-version` to at least 2.7.7 too as we know that works.

**Comment by malikarun** [comment]
> we should try for 3.2 support

Alright I have updated the PR to include ruby `['>= 2.7.7', '< 3.3']`. Creating an instance with and without data still work. Updated the `.ruby-version` to `2.7.7`

@nathanaelkane @jasoncodes 
if that looks good, we can merge it now?  

Builds:
https://buildkite.com/ennova/awesome-branch/builds/20370
https://buildkite.com/ennova/awesome-branch/builds/20371

**Comment by nathanaelkane** [comment]
I'm good with it, but probably best to hear from @jasoncodes first as he was doing some isolated testing.

**Comment by jasoncodes** [comment]
Changes look good. I’m doing some manual testing with Enops to see how it fairs with Ruby 3.x. If I find any issues I’ll drop some patches here for review. If all good, I’ll merge.

**Comment by jasoncodes** [comment]
Okay, I’ve done some manual testing of both the runner/restore code as well as our Heroku API wrapper on both 2.7.7 and 3.2.0 RC1. A couple of minor patches required to run things in isolation on Ruby 3 but otherwise, all good.

**Review by jasoncodes — APPROVED** [review]

**Pull request merged**
